### ISSUE TITLE
Astar Planner failed to build

### ISSUE THREAD

**Issue by shehrozbashir546** [ctu-mrs/mrs_octomap_planner#1]
I am implementing the MRS Octomap Planner in a separate environment. I cloned the mrs_msgs, mrs_lib and mrs_octomap_planner into a fresh catkin workspace. After installing any required dependencies, my catkin build failed. It gives me the following error. I have implemented and ran the mrs_uav_system using singularity and ran into no issues.
Interestingly, my catkin build sometimes gives me the output that 'PCL does not exist on this machine'
This is the error I got when I commented out the "find_package(PCL REQUIRED)" in the CMakeLists.txt file.
![Screenshot from 2022-08-23 14-36-53](https://user-images.githubusercontent.com/49991357/186173656-36770cc0-6997-4917-87f5-3a1c5a54205c.png)
And this is what I get when I uncomment it 
![pclerror](https://user-images.githubusercontent.com/49991357/186174768-84b8790b-ea3e-4558-a5c8-981b29690f11.png)

**Comment by spurnvoj** [comment]
Hi, we are building our own version of the `octomap` and `octomap_server`. Check this package that has all packages that we are using for octomap_mapping and planning https://github.com/ctu-mrs/octomap_mapping_planning. You will probably need almost all of them if you want to use the planner.

**Comment by shehrozbashir546** [comment]
> Hi, we are building our own version of the `octomap` and `octomap_server`. Check this package that has all packages that we are using for octomap_mapping and planning https://github.com/ctu-mrs/octomap_mapping_planning. You will probably need almost all of them if you want to use the planner.

Hi, Thanks for your prompt response. I cloned that library in a fresh workspace. Catkin Build required me to git clone two additional libraries: mrs_msgs and mrs_libs. I suggest you add these to this repo if you need this to work standalone. 

Unfortunately, catkin build failed. I have attached the log files I will include a screenshot that display the crux of the situation.

![error_screenshot](https://user-images.githubusercontent.com/49991357/186396118-b10991b2-742b-44b9-90b8-624002f48ed4.png)



[build.cmake.001 (octomap_rviz_plugins).log](https://github.com/ctu-mrs/mrs_octomap_planner/files/9415230/build.cmake.001.octomap_rviz_plugins.log)

**Comment by spurnvoj** [comment]
`mrs_lib` and `mrs_msgs` are part of our core packages that are in `uav_core`. We have every time core installed on our PCs. Therefore, it is not required to have them as a part of `octomap_mapping_planning`. The error tells you that CMake cannot find boost thread library. Check that you have installed `libboost-thread-dev` in your system.

**Comment by klaxalk** [comment]
Hey, this planner package is part of the [https://github.com/ctu-mrs/octomap_mapping_planning](https://github.com/ctu-mrs/octomap_mapping_planning) metapackage. That depends on the uav_core and possibly UAV modules (for sensor drivers and PCL processing). Therefore, we don't want to be a standalone thing, it is more like an addition to the uav_core. It would be hard to make it standalone since just the planner package relies on real-time trajectory predictions from the MPC Tracker to prevent collisions.

If you can, pull the latest changes in the octomap_mapping_planning, I fixed a serious runtime problem yesterday.

**Comment by shehrozbashir546** [comment]
Thanks for the update. I have a persistent problem with my Boost libraries despite updating it and reinstalling.
CMake Error in CMakeLists.txt:
  Imported target "Boost::thread" includes non-existent path

    "/include"

I believe this is an isolated incident on my machine (Ubuntu 20.04 ROS Noetic libboostdev 1.71). I will switch to the singularity image and amend it to my workflow. My goal is to use the octomap planner you have developed on UGVs. I will close this issue in 2 days.

**Comment by shehrozbashir546** [comment]
In case any one else is wondering, the steps i followed were:
1) clone uav core and modules
2) run their respective install.sh
3) catkin build
4) clone octomap plannner
5) step 2 and 3
